[project]
name = "inventory_scanner"
version = "0.1.0"
root = "inventory_scanner.core"

[modules]
paths = ["./dsl"]

[stack]
name = "dnr"

[auth]
enabled = true
provider = "session"
allow_registration = true
